In [2]:
print("Hello World")

Hello World


In [3]:
import torch
print(torch.__version__)


2.9.0


In [4]:
import pandas as pd
print(pd.__version__)

2.3.2


In [5]:
import torch

# 创建一个 2x3 的全 0 张量
a = torch.zeros(2, 3)
print(a)

# 创建一个 2x3 的全 1 张量
b = torch.ones(2, 3)
print(b)

# 创建一个 2x3 的随机数张量
c = torch.randn(2, 3)
print(c)

# 从 NumPy 数组创建张量
import numpy as np
numpy_array = np.array([[1, 2], [3, 4]])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)

# 在指定设备（CPU/GPU）上创建张量
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
d = torch.randn(2, 3, device=device)
print(d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 1.7910, -0.3036, -0.1813],
        [ 0.9189, -0.3008, -0.5107]])
tensor([[1, 2],
        [3, 4]])
tensor([[ 1.6432,  0.2384, -0.6296],
        [ 0.2016, -0.3306, -0.0441]])


In [11]:
# 张量相加
e = torch.randn(2, 3)
f = torch.randn(2, 3)
print(e + f)

# 逐元素乘法
print(e * f)

# 张量的转置
g = torch.randn(3, 2)
print(g.t())  # 或者 g.transpose(0, 1)

# 张量的形状
print(g.shape)  # 返回形状

tensor([[-0.3633, -2.1304,  0.6932],
        [-0.1541,  1.2439, -0.3141]])
tensor([[-0.3356,  1.1334, -0.4482],
        [-0.0590,  0.2084, -0.3686]])
tensor([[ 0.2794,  1.9988,  0.7970],
        [-1.8426, -0.6568, -2.1344]])
torch.Size([3, 2])


In [13]:
# 创建一个需要梯度的张量
tensor_requires_grad = torch.tensor([1.0], requires_grad=True)

# 进行一些操作
tensor_result = tensor_requires_grad * 2

# 计算梯度
tensor_result.backward()
print(tensor_requires_grad.grad)  # 输出梯度

tensor([2.])


In [19]:
# 创建一个需要计算梯度的张量
x = torch.randn(2, 2, requires_grad=True)
print(x)

# 执行某些操作
y = x + 2
z = y * y * 3
out = z.mean()

print(out)

tensor([[0.0762, 0.3416],
        [0.0972, 0.2568]], requires_grad=True)
tensor(14.4638, grad_fn=<MeanBackward0>)


In [20]:
# 反向传播，计算梯度
out.backward()

# 查看 x 的梯度
print(x.grad)

tensor([[3.1142, 3.5124],
        [3.1458, 3.3853]])


In [22]:
# 使用 torch.no_grad() 禁用梯度计算
with torch.no_grad():
    y = x * 2

In [24]:
import torch.nn as nn
import torch.optim as optim

# 定义一个简单的全连接神经网络
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 2)  # 输入层到隐藏层
        self.fc2 = nn.Linear(2, 1)  # 隐藏层到输出层

    def forward(self, x):
        x = torch.relu(self.fc1(x))  # ReLU 激活函数
        x = self.fc2(x)
        return x

# 创建网络实例
model = SimpleNN()

# 打印模型结构
print(model)

SimpleNN(
  (fc1): Linear(in_features=2, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=1, bias=True)
)


In [28]:
# 随机输入
x = torch.randn(1, 2)

# 前向传播
output = model(x)
print(output)

# 定义损失函数（例如均方误差 MSE）
criterion = nn.MSELoss()

# 假设目标值为 1
target = torch.randn(1, 1)

# 计算损失
loss = criterion(output, target)
print(loss)

tensor([[-0.3316]], grad_fn=<AddmmBackward0>)
tensor(0.1928, grad_fn=<MseLossBackward0>)


In [29]:
# 定义优化器（使用 Adam 优化器）
optimizer = optim.Adam(model.parameters(), lr=0.001)

# 训练步骤
optimizer.zero_grad()  # 清空梯度
loss.backward()  # 反向传播
optimizer.step()  # 更新参数

In [30]:
import torch
import torch.nn as nn
import torch.optim as optim

# 1. 定义一个简单的神经网络模型
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 2)  # 输入层到隐藏层
        self.fc2 = nn.Linear(2, 1)  # 隐藏层到输出层

    def forward(self, x):
        x = torch.relu(self.fc1(x))  # ReLU 激活函数
        x = self.fc2(x)
        return x

# 2. 创建模型实例
model = SimpleNN()

# 3. 定义损失函数和优化器
criterion = nn.MSELoss()  # 均方误差损失函数
optimizer = optim.Adam(model.parameters(), lr=0.001)  # Adam 优化器

# 4. 假设我们有训练数据 X 和 Y
X = torch.randn(10, 2)  # 10 个样本，2 个特征
Y = torch.randn(10, 1)  # 10 个目标值

# 5. 训练循环
for epoch in range(100):  # 训练 100 轮
    optimizer.zero_grad()  # 清空之前的梯度
    output = model(X)  # 前向传播
    loss = criterion(output, Y)  # 计算损失
    loss.backward()  # 反向传播
    optimizer.step()  # 更新参数

    # 每 10 轮输出一次损失
    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/100], Loss: {loss.item():.4f}')

Epoch [10/100], Loss: 0.7370
Epoch [20/100], Loss: 0.7240
Epoch [30/100], Loss: 0.7128
Epoch [40/100], Loss: 0.7035
Epoch [50/100], Loss: 0.6956
Epoch [60/100], Loss: 0.6890
Epoch [70/100], Loss: 0.6834
Epoch [80/100], Loss: 0.6786
Epoch [90/100], Loss: 0.6742
Epoch [100/100], Loss: 0.6702


In [31]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 将模型移动到设备
model.to(device)

# 将数据移动到设备
X = X.to(device)
Y = Y.to(device)

In [1]:
print("Hello World")
print("Hello World")
print("Hello World")

Hello World
Hello World
Hello World


In [ ]:
print("Hello World!")
